export type MockCampaign = {
  id: string;
  name: string;
  author: string;
  description: string;
  createdAt: string;
  artworkCount: number;
  lastPrompt: string;
};

export const mockCampaigns: MockCampaign[] = [
  {
    id: "spring-launch",
    name: "Spring launch",
    author: "Ava Johnson",
    description: "Campaign imagery for the new spring collection launch.",
    createdAt: "Mar 18, 2026",
    artworkCount: 4,
    lastPrompt: "Editorial still life with fresh botanicals and soft morning light.",
  },
  {
    id: "city-after-dark",
    name: "City after dark",
    author: "Maya Singh",
    description: "Night-time campaign concepts for the urban essentials range.",
    createdAt: "Mar 12, 2026",
    artworkCount: 6,
    lastPrompt: "Architectural cityscape at blue hour with luminous reflections.",
  },
  {
    id: "weekend-rituals",
    name: "Weekend rituals",
    author: "Noah Williams",
    description: "A relaxed lifestyle series for seasonal weekend moments.",
    createdAt: "Mar 4, 2026",
    artworkCount: 3,
    lastPrompt: "Warm candid table scene with textured linens and afternoon sun.",
  },
  {
    id: "summer-stories",
    name: "Summer stories",
    author: "Liam Chen",
    description: "Bright social assets for the summer travel collection.",
    createdAt: "Feb 27, 2026",
    artworkCount: 5,
    lastPrompt: "Sunlit coastal scenes with candid motion and saturated color.",
  },
  {
    id: "quiet-luxury",
    name: "Quiet luxury",
    author: "Sofia Martinez",
    description: "A refined visual direction for the signature essentials edit.",
    createdAt: "Feb 20, 2026",
    artworkCount: 8,
    lastPrompt: "Minimal product still life with warm stone and soft shadows.",
  },
  {
    id: "morning-routine",
    name: "Morning routine",
    author: "Ethan Brooks",
    description: "Short-form creative concepts for an everyday wellness launch.",
    createdAt: "Feb 14, 2026",
    artworkCount: 4,
    lastPrompt: "Calm morning desk scene with natural light and ceramic details.",
  },
  {
    id: "festival-edit",
    name: "Festival edit",
    author: "Olivia King",
    description: "Bold announcement assets for the upcoming city festival.",
    createdAt: "Feb 8, 2026",
    artworkCount: 7,
    lastPrompt: "Energetic crowd silhouettes, graphic light, and vivid color fields.",
  },
  {
    id: "fresh-start",
    name: "Fresh start",
    author: "Daniel Park",
    description: "New-year campaign concepts for home organisation products.",
    createdAt: "Jan 30, 2026",
    artworkCount: 3,
    lastPrompt: "Airy organised home interior with crisp daylight and neutral tones.",
  },
  {
    id: "winter-weekends",
    name: "Winter weekends",
    author: "Grace Wilson",
    description: "Cozy editorial scenes for the cold-weather collection.",
    createdAt: "Jan 22, 2026",
    artworkCount: 6,
    lastPrompt: "Warm knit textures, candlelight, and a softly blurred winter view.",
  },
  {
    id: "studio-notes",
    name: "Studio notes",
    author: "Henry Adams",
    description: "Behind-the-scenes creative for a maker-focused product story.",
    createdAt: "Jan 16, 2026",
    artworkCount: 4,
    lastPrompt: "Artist studio workspace with paper sketches, tools, and daylight.",
  },
  {
    id: "neighbourhood-guide",
    name: "Neighbourhood guide",
    author: "Mia Thompson",
    description: "Local discovery content for the community partnerships program.",
    createdAt: "Jan 9, 2026",
    artworkCount: 5,
    lastPrompt: "Friendly street-level scenes with independent shops and locals.",
  },
  {
    id: "product-focus",
    name: "Product focus",
    author: "Leo Grant",
    description: "Detail-led product assets for a focused retail launch.",
    createdAt: "Dec 19, 2025",
    artworkCount: 9,
    lastPrompt: "Clean product close-ups with dramatic directional studio lighting.",
  },
  {
    id: "gift-guide",
    name: "Gift guide",
    author: "Ella Roberts",
    description: "Seasonal recommendation creatives for thoughtful gifting.",
    createdAt: "Dec 12, 2025",
    artworkCount: 6,
    lastPrompt: "Curated gift boxes with tactile wrapping paper and ribbon details.",
  },
  {
    id: "after-hours",
    name: "After hours",
    author: "Jacob Reed",
    description: "Evening social concepts for the late-night service window.",
    createdAt: "Dec 5, 2025",
    artworkCount: 4,
    lastPrompt: "Moody evening storefront with warm pools of light and rain.",
  },
  {
    id: "member-moments",
    name: "Member moments",
    author: "Zoe Patel",
    description: "Community highlights that celebrate loyal members.",
    createdAt: "Nov 28, 2025",
    artworkCount: 7,
    lastPrompt: "Candid portraits of a diverse community in natural daylight.",
  },
];
